---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    login_cmd_template: 'bash'
    ansible_connection_options:
      connection: local
platforms:
  - name: localhost
lint:
  name: yamllint
provisioner:
  name: ansible
  env:
    MOLECULE_DEBUG: 'False'
    #  options:
    #    vvv: 'True'
  playbooks:
    create: create.yml
    destroy: destroy.yml
    converge: playbook.yml
  config_options:
    defaults:
      retry_files_enabled: 'False'
      ansible_connection: local
  inventory:
    host_vars:
      localhost:
        security_rhel7_initialize_aide: 'yes'
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
    connection: local
  lint:
    name: flake8
